language: python

services:
- postgresql

install: pip install -r requirements.txt

before_script:

before_script:
  - psql -c 'create database event_meet_db;' -U postgres
  - python manage.py migrate --noinput

script:
  - python manage.py test
